### ISSUE TITLE
提交博客/微信公众号信息

### ISSUE THREAD

**Issue by yangwenmai** [yangwenmai/golangBlogCN#1]
请按以下格式提交博客/微信公众号信息：

博客Title:
博客地址:
RSS聚合地址:
博主微博地址（选填）:
博主twitter地址（选填）:

----

微信公众号名称：
微信公众号ID：
微信公众号二维码地址：

----

资料说明：
URL 地址：

**Comment by biganxin** [comment]
Welcome the best developers to the PlatON ecosystem
https://github.com/LatticeX-Foundation/dev-bounties/blob/main/Developer%20Bounty%20Program(Phase-I).md
