### ISSUE TITLE
Go书籍专栏可以考虑增加《Go 101》

### ISSUE THREAD

**Issue by domac** [yangwenmai/golangBlogCN#2]
Hi~ learning-golang的“Go书籍”专栏可以考虑增加Go 101的链接：

[《Go 101》](https://go101.org/article/101.html)这本在线书籍更多关注Go的一些细节知识点，个人感觉可以作为进阶学习的资料

同时这书也是一个开源项目：https://github.com/go101/go101

**Comment by yangwenmai** [comment]
已添加到[https://github.com/developer-learning/learning-golang](https://github.com/developer-learning/learning-golang)，谢谢分享。
